In [ ]:
import pandas as pd #import pandas library

In [ ]:
ola=pd.read_csv('/content/Ola Customer Reviews.csv')

/tmp/ipython-input-2146553033.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  ola=pd.read_csv('/content/Ola Customer Reviews.csv')

In [ ]:
ola

,source,review_id,user_name,review_title,review_description,rating,thumbs_up,review_date,developer_response,developer_response_date,appVersion,laguage_code,country_code
0,Google Play,fbc7ffc9-5a89-446e-87fd-d69bf4a7f984,Puipuii Ralte,NaN,"The map in Ola is so messed up, i have to pay ...",1,0.0,2023-08-10 16:40:50,NaN,NaN,6.3.2,en,in
1,Google Play,5a0051fb-220a-45b2-ba94-a15a2949218f,Deepak Kumar,NaN,Deepak Kumar.... 🙏🙏🙏🙏🙏],5,0.0,2023-08-10 16:36:14,NaN,NaN,NaN,en,in
2,Google Play,71ebf933-b734-474d-bb65-a18c90906ed2,Ahamed Azarudeen,NaN,Such aa irresponsible app more then I waiting ...,1,0.0,2023-08-10 16:29:31,NaN,NaN,6.3.1,en,in
3,Google Play,e1cc0010-60b3-4126-99c2-e8549088566a,Rahil Syed,NaN,Worst,1,0.0,2023-08-10 15:52:06,NaN,NaN,5.0.4,en,in
4,Google Play,77cf1be1-b428-4493-ae25-e0f288f79b8f,vin 007,NaN,Too much expensive .. try UBer... They are pro...,1,0.0,2023-08-10 15:51:10,NaN,NaN,NaN,en,in
...,...,...,...,...,...,...,...,...,...,...,...,...,...
357693,App Store,575258ed-aec1-47ea-b792-88deb17e4ad7,Jayken17,Can't sign up with App200 code,The app is useless for new users since you can...,1,NaN,2015-03-08 04:33:32,NaN,NaN,NaN,en,in
357694,App Store,ca91ebc0-92d9-48a6-9c46-7dcad1a0546e,cbarath1986,Worst app n online services,Do not recharge money with ola money.. I have ...,1,NaN,2015-03-02 23:13:22,NaN,NaN,NaN,en,in
357695,App Store,f7227b64-90aa-4c82-996e-c86d99761831,MaS Mitt,Signup itself is so difficult,The app hangs on signup. Later I get authentic...,2,NaN,2015-03-02 11:52:50,NaN,NaN,NaN,en,in
357696,App Store,5f14c66e-94cc-4594-a83e-055ab8721ca8,vasantha2,Worst iphone App,one of the worst app for iphone.i was tried mu...,1,NaN,2015-02-17 15:17:12,NaN,NaN,NaN,en,in
357697,App Store,b4f2a564-e5aa-48d5-bbc0-8b8e2751628e,June Day,Hopeless,This company is hopeless. I waited on hold for...,1,NaN,2014-10-16 08:53:01,NaN,NaN,NaN,en,in

In [ ]:
ola.columns

Index(['source', 'review_id', 'user_name', 'review_title',
       'review_description', 'rating', 'thumbs_up', 'review_date',
       'developer_response', 'developer_response_date', 'appVersion',
       'laguage_code', 'country_code'],
      dtype='object')

In [ ]:
ola=ola.drop(columns=['source','review_id','review_title','user_name','thumbs_up','developer_response', 'developer_response_date', 'appVersion',
       'laguage_code', 'country_code'])

In [ ]:
ola

,review_description,rating,review_date
0,"The map in Ola is so messed up, i have to pay ...",1,2023-08-10 16:40:50
1,Deepak Kumar.... 🙏🙏🙏🙏🙏],5,2023-08-10 16:36:14
2,Such aa irresponsible app more then I waiting ...,1,2023-08-10 16:29:31
3,Worst,1,2023-08-10 15:52:06
4,Too much expensive .. try UBer... They are pro...,1,2023-08-10 15:51:10
...,...,...,...
357693,The app is useless for new users since you can...,1,2015-03-08 04:33:32
357694,Do not recharge money with ola money.. I have ...,1,2015-03-02 23:13:22
357695,The app hangs on signup. Later I get authentic...,2,2015-03-02 11:52:50
357696,one of the worst app for iphone.i was tried mu...,1,2015-02-17 15:17:12
357697,This company is hopeless. I waited on hold for...,1,2014-10-16 08:53:01

In [ ]:
ola.isnull().sum()

review_description    20
rating                 0
review_date            0
dtype: int64

In [ ]:
ola.isnull().any()

review_description     True
rating                False
review_date           False
dtype: bool

In [ ]:
ola.dropna(inplace=True)

In [ ]:
ola.isnull().sum()

review_description    0
rating                0
review_date           0
dtype: int64

In [ ]:
def rating_to_sentiment(r):
    if r >= 4:
        return "positive"
    elif r == 3:
        return "neutral"
    else:
        return "negative"

ola["sentiment"] = ola["rating"].apply(rating_to_sentiment)

In [ ]:
ola

,review_description,rating,review_date,sentiment
0,"The map in Ola is so messed up, i have to pay ...",1,2023-08-10 16:40:50,negative
1,Deepak Kumar.... 🙏🙏🙏🙏🙏],5,2023-08-10 16:36:14,positive
2,Such aa irresponsible app more then I waiting ...,1,2023-08-10 16:29:31,negative
3,Worst,1,2023-08-10 15:52:06,negative
4,Too much expensive .. try UBer... They are pro...,1,2023-08-10 15:51:10,negative
...,...,...,...,...
357693,The app is useless for new users since you can...,1,2015-03-08 04:33:32,negative
357694,Do not recharge money with ola money.. I have ...,1,2015-03-02 23:13:22,negative
357695,The app hangs on signup. Later I get authentic...,2,2015-03-02 11:52:50,negative
357696,one of the worst app for iphone.i was tried mu...,1,2015-02-17 15:17:12,negative
357697,This company is hopeless. I waited on hold for...,1,2014-10-16 08:53:01,negative

In [ ]:
x=ola['review_description']
y=ola['sentiment']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=ola['sentiment'])

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=10000,
    ngram_range=(1, 2)
)

In [ ]:
x_train_tfidf = tfidf.fit_transform(x_train)
x_test_tfidf = tfidf.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

model.fit(x_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
from sklearn.metrics import classification_report, accuracy_score

y_pred = model.predict(x_test_tfidf)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8937737642585551
              precision    recall  f1-score   support

    negative       0.90      0.94      0.92     37757
     neutral       0.35      0.01      0.01      3198
    positive       0.88      0.93      0.91     30581

    accuracy                           0.89     71536
   macro avg       0.71      0.63      0.61     71536
weighted avg       0.87      0.89      0.87     71536

In [ ]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

Confusion Matrix:
[[35252    27  2478]
 [ 1661    13  1524]
 [ 2036    16 28529]]